version: '3'

services:
  caddy:
    image: benzbrake/caddy
    container_name: caddy
    restart: always
    volumes:
      - /data/wwwroot/myweb:/www/wwwroot/myweb
      - /data/wwwlogs:/www/wwwlogs
      - /data/wwwconf:/www/config
    ports:
      - "80:80"
      - "443:443"