version: '3'

services:
  caddyphp:
    image: benzbrake/caddy:php
    container_name: caddyphp
    restart: always
    volumes:
      - /data/caddypath:/root/.caddy
      - /data/wwwroot/myweb:/www/wwwroot/myweb
      - /data/wwwlogs:/www/wwwlogs
      - /data/wwwconf:/www/config
    ports:
      - "80:80"
      - "443:443"